development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5

production:
  adapter: postgresql
  database: sample_app_production
  pool: 5

cucumber:
  <<: *test